// QrCameraPro.h
// Native TurboModule header for the QR/Barcode scanner module.
//
// Conforms to NativeQrCameraProSpec (generated by Codegen) and inherits from
// RCTEventEmitter so the module can push events (onBarcodeScanned, onCameraError)
// to the JavaScript side without polling.

#import <Foundation/Foundation.h>
#import <React/RCTEventEmitter.h>

#ifdef __cplusplus
#import <QrCameraProSpec/QrCameraProSpec.h>
#endif

/// Objective-C–visible interface for the QR/Barcode scanner TurboModule.
/// The implementation lives in QrCameraPro.mm and delegates all AVFoundation
/// work to the Swift singleton QrCameraProSwift.
@interface QrCameraPro : RCTEventEmitter
#ifdef __cplusplus
<NativeQrCameraProSpec>
#endif

@end