// QrCameraPro.mm
// Objective-C++ TurboModule implementation for the QR/Barcode scanner.
//
// Responsibilities (SRP):
//   • Expose the module to React Native's TurboModule infrastructure.
//   • Forward JS method calls to QrCameraProSwift (the real implementation).
//   • Manage the RCTEventEmitter lifecycle (listener counting, observing hooks).
//
// All AVFoundation logic lives in QrCameraProSwift.swift — this file is
// intentionally kept as thin as possible (KISS / SRP).

#import "QrCameraPro.h"
#import <AVFoundation/AVFoundation.h>

// Import the Swift–ObjC bridge header generated by Xcode.
#if __has_include("QrCameraPro-Swift.h")
#import "QrCameraPro-Swift.h"
#else
#import <QrCameraPro/QrCameraPro-Swift.h>
#endif

@implementation QrCameraPro

#pragma mark - Public JS-callable Methods

/// Wires this emitter to the Swift singleton and starts the camera session.
/// Called from JavaScript via NativeModules.QrCameraPro.startScanning().
- (void)startScanning {
    [QrCameraProSwift.shared setEventEmitter:self];
    [QrCameraProSwift.shared startScanning];
}

/// Stops the capture session and releases camera resources.
/// Called from JavaScript via NativeModules.QrCameraPro.stopScanning().
- (void)stopScanning {
    [QrCameraProSwift.shared stopScanning];
}

/// Turns the device torch on or off.
/// @param enabled YES to turn the torch on, NO to turn it off.
- (void)toggleTorch:(BOOL)enabled {
    [QrCameraProSwift.shared toggleTorch:enabled];
}

#pragma mark - RCTEventEmitter Listener Lifecycle

/// Called by RCTEventEmitter when a JS subscriber adds a listener.
/// Must call super so the internal listener count is incremented correctly;
/// without it the count stays at 0 and every sendEvent() logs a warning.
/// RCTEventEmitter automatically calls -startObserving when count goes 0 → 1.
- (void)addListener:(NSString *)eventName {
    [super addListener:eventName];
}

/// Called by RCTEventEmitter when JS subscribers are removed.
/// Must call super so the internal count is decremented correctly;
/// RCTEventEmitter automatically calls -stopObserving when count reaches 0.
- (void)removeListeners:(double)count {
    [super removeListeners:count];
}

/// Called by RCTEventEmitter when the first JS listener is registered (count 0 → 1).
/// Signals the Swift layer that it can now safely emit events to JS.
/// This closes the timing gap between startScanning() and the JS useEffect
/// registering its first listener.
- (void)startObserving {
    [QrCameraProSwift.shared setHasListeners:YES];
}

/// Called by RCTEventEmitter when the last JS listener is removed (count → 0).
/// Signals the Swift layer to stop emitting, preventing spurious warnings after
/// the component unmounts.
- (void)stopObserving {
    [QrCameraProSwift.shared setHasListeners:NO];
}

#pragma mark - RCTEventEmitter Required Overrides

/// Declares the events this module can emit to JavaScript.
/// Must match the event names used in QrCameraProSwift's sendEvent calls.
- (NSArray<NSString *> *)supportedEvents {
    return @[@"onBarcodeScanned", @"onCameraError"];
}

#pragma mark - TurboModule Infrastructure

/// Returns the C++ TurboModule implementation bound to this Obj-C instance.
/// Required by the New Architecture (JSI / TurboModule) to replace the legacy bridge.
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeQrCameraProSpecJSI>(params);
}

/// Returns the module name registered with React Native's module registry.
/// Must match the name used in the JS NativeModule spec.
+ (NSString *)moduleName {
    return @"QrCameraPro";
}

@end